CC       := $(LFI_ROOT)/aarch64-lfi-clang/bin/clang
CXX      := $(LFI_ROOT)/aarch64-lfi-clang/bin/clang++
AS       := $(LFI_ROOT)/aarch64-lfi-clang/bin/clang
AR       := $(LFI_ROOT)/aarch64-lfi-clang/bin/llvm-ar
STRIP    := $(LFI_ROOT)/aarch64-lfi-clang/bin/llvm-strip

include Makefile

PREFIX   = /home/talg/repo/lfi-bench/benchmark-lib/aarch64-lfi-clang
